spring:
    profiles:
        active: local
    application:
        name: Message's Microservice

app:
    name: Message's Microservice
    version: 0.0.1
    description: Microservice for managing messages